### PR TITLE
Zubee's Assignment

### PR DESCRIPTION
**Pull request by Zubee-max**
The differences between Maven and Gradle.

### CODE REVIEW

**Comment by Zubee-max** [comment]
This is ok.

**Comment by Newerasolutiona** [comment]
Nice work, Azubuike.

**Comment by Newerasolutiona** [comment]
Zubby, You didn't quite get the structure of the assignmet. You were supposed to create a directory - corresponding to your name - and place the file containing your assignment inside the directory.

**Comment by Zubee-max** [comment]
Tanx for the review Prof.

I actually thought I created the assignment file (Assignment.txt) in
Azubike's directory.
Will go through it again.

**Comment by Zubee-max** [comment]
Ok Prof, I see what you're saying now.
I created my assignment file in Class14-Assignment1 directory instead of
Azubike directory.

Tanx again.

**Pull request merged**
